### ISSUE TITLE
Supported PEM Type not found #206

### ISSUE THREAD

**Issue by RezaErfani67** [davesag/jose-simple#13]
```javascript
var keys= keypair();
JWK.asKey(keys.public,'pem').then(function(result){
console.log(result);        
})
```

this give error:
Supported PEM Type not found

i am using [keypair](https://www.npmjs.com/package/keypair)  to generate keys

**Comment by davesag** [comment]
That's really an issue for the [`node-jose`](https://github.com/cisco/node-jose) package which is a dependency of this package.

If you look in my tests of this library you can see the following code

```
const keygen = require('generate-rsa-keypair')
const { JWK } = require('node-jose')

const makeKey = pem => JWK.asKey(pem, 'pem')
```

which I then use below

```
  const keys = keygen()

  const jwKeys = await Promise.all([
    makeKey(keys.public),
    makeKey(keys.private)
  ])
```

so your issue might be with the `keypair` function, or the `JWK` library.

Cheers

Dave

**Comment by RezaErfani67** [comment]
generate-rsa-keypair is deprecated.
so its better to change your test sample with new library like "keypair"

**Comment by davesag** [comment]
I just looked at https://github.com/LinusU/node-generate-rsa-keypair#readme and there is no mention of it being deprecated, and I don't get any deprecation warnings when I run my tests.

**Comment by RezaErfani67** [comment]
i'm wonder about this... 
ok thank you
