### ISSUE TITLE
Add Encryption option to allow format to be specified

### ISSUE THREAD

**Issue by gschmottlach-xse** [davesag/jose-simple#35]
Could you add an option to your *encrypt()* function which would allow a user to specify the format of the encrypted JWE. Right now it seems to (default) to JWE JSON Serialization. It would be nice if an alternate format could be specified such as JWE Compact Serialization. I think the only change that needs to be made is to pass an extra options argument to JWE.createEncrypt(). For the case of using JWE Compact serialization it would look like:

const encrypted = await JWE.createEncrypt({ format: 'compact'}, publicKey)

Perhaps just providing a way to pass in an *options* object to the *encrypt()* function might suffice and provide the most future-proof approach should other options need to be changed.

I liked you're "simplier" approach to using JWE's . . . thanks for the contribution!

**Comment by davesag** [comment]
Good suggestion.  I'll take a look at this.

**Comment by davesag** [comment]
completed in version 1.2.0

**Comment by gschmottlach-xse** [comment]
Thanks for adding this . . .
